sudo: required
dist: trusty
language: node_js
node_js:
  - "8.5.0"
env:
    - EMBER_VERSION=default
    - EMBER_VERSION=release
    - EMBER_VERSION=beta
    - EMBER_VERSION=canary
matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_VERSION=release
    - env: EMBER_VERSION=beta
    - env: EMBER_VERSION=canary

before_install:
    - "npm config set spin false"
    - "npm install -g npm@5.3.0"
install:
    - npm install
script:
    - npm test
