sudo: required
dist: trusty
language: node_js
node_js:
  - "8.5.0"
before_install:
    - "npm config set spin false"
    - "npm install -g npm@5.6.0"
install:
    - npm install
script:
    - npm test

